[workspace]
authors = ["Thiago Nascimento <dungeoncraw@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "layouts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2026010517,<0.27"
