[workspace]
authors = ["Thiago Nascimento <dungeoncraw@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "simd"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026022205,<0.27"
